# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.28.0"
StyLua = "JohnnyMorganz/StyLua@2.1.0"
rojo = "UpliftGames/rojo@7.3.0-uplift.11"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
